name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RACE_STRATAGY_APP }}
          channelId: dev
          projectId: race-stratagy-app
